<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: game_service.proto

namespace GPBMetadata;

class GameService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\x87\x03\x0A\x12game_service.proto\x12\x04game\" \x0A\x0EGetGameRequest\x12\x0E\x0A\x06gameId\x18\x01 \x01(\x09\"m\x0A\x10GameInfoResponse\x12\x0E\x0A\x06gameId\x18\x01 \x01(\x09\x12\x0E\x0A\x06status\x18\x02 \x01(\x09\x12\x12\x0A\x0AmaxPlayers\x18\x03 \x01(\x05\x12\x13\x0A\x0BtotalRounds\x18\x04 \x01(\x05\x12\x10\x0A\x08turnTime\x18\x05 \x01(\x05\"\"\x0A\x10CheckGameRequest\x12\x0E\x0A\x06gameId\x18\x01 \x01(\x09\"#\x0A\x11CheckGameResponse\x12\x0E\x0A\x06exists\x18\x01 \x01(\x082\x88\x01\x0A\x0BGameService\x12<\x0A\x09CheckGame\x12\x16.game.CheckGameRequest\x1A\x17.game.CheckGameResponse\x12;\x0A\x0BGetGameInfo\x12\x14.game.GetGameRequest\x1A\x16.game.GameInfoResponseb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

