<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_service.proto

namespace App\Grpc\GPBMetadata;

class UserService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xE7\x02\x0A\x12user_service.proto\x12\x05users\"%\x0A\x10CheckUserRequest\x12\x11\x0A\x09sessionId\x18\x01 \x01(\x09\"\"\x0A\x11CheckUserResponse\x12\x0D\x0A\x05check\x18\x01 \x01(\x02\"\x1E\x0A\x10CheckByIdRequest\x12\x0A\x0A\x02id\x18\x01 \x01(\x05\"\"\x0A\x11CheckByIdResponse\x12\x0D\x0A\x05check\x18\x01 \x01(\x022\x8E\x01\x0A\x0CUsersService\x12>\x0A\x09CheckUser\x12\x17.users.CheckUserRequest\x1A\x18.users.CheckUserResponse\x12>\x0A\x09CheckById\x12\x17.users.CheckByIdRequest\x1A\x18.users.CheckByIdResponseB\"\xCA\x02\x08App\\Grpc\xE2\x02\x14App\\Grpc\\GPBMetadatab\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

