<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_service.proto

namespace GPBMetadata;

class UserService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad1010a12757365725f736572766963652e70726f746f12096d797365727669636522220a0f55736572496e666f52657175657374120f0a07757365725f6964180120012809222f0a1055736572496e666f526573706f6e7365120c0a046e616d65180120012809120d0a05656d61696c18022001280932530a094d795365727669636512460a0b47657455736572496e666f121a2e6d79736572766963652e55736572496e666f526571756573741a1b2e6d79736572766963652e55736572496e666f526573706f6e7365620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

