<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_service.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>CheckByIdResponse</code>
 */
class CheckByIdResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>float check = 1;</code>
     */
    protected $check = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $check
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\UserService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>float check = 1;</code>
     * @return float
     */
    public function getCheck()
    {
        return $this->check;
    }

    /**
     * Generated from protobuf field <code>float check = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setCheck($var)
    {
        GPBUtil::checkFloat($var);
        $this->check = $var;

        return $this;
    }

}

