<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_service.proto

namespace App\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>users.CheckUserRequest</code>
 */
class CheckUserRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string sessionId = 1;</code>
     */
    protected $sessionId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $sessionId
     * }
     */
    public function __construct($data = NULL) {
        \App\Grpc\GPBMetadata\UserService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string sessionId = 1;</code>
     * @return string
     */
    public function getSessionId()
    {
        return $this->sessionId;
    }

    /**
     * Generated from protobuf field <code>string sessionId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSessionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->sessionId = $var;

        return $this;
    }

}

