<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: user_service.proto

namespace Myservice;

use Spiral\RoadRunner\GRPC;

interface MyServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "myservice.MyService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param UserInfoRequest $in
    * @return UserInfoResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function GetUserInfo(GRPC\ContextInterface $ctx, UserInfoRequest $in): UserInfoResponse;
}
