// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v7.34.0
// source: proto/user.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "users";

export interface CheckUserRequest {
  sessionId: string;
}

export interface CheckUserResponse {
  check: number;
}

export interface CheckByIdRequest {
  id: number;
}

export interface CheckByIdResponse {
  check: number;
}

export const USERS_PACKAGE_NAME = "users";

export interface UsersServiceClient {
  checkUser(request: CheckUserRequest): Observable<CheckUserResponse>;

  checkById(request: CheckByIdRequest): Observable<CheckByIdResponse>;
}

export interface UsersServiceController {
  checkUser(request: CheckUserRequest): Promise<CheckUserResponse> | Observable<CheckUserResponse> | CheckUserResponse;

  checkById(request: CheckByIdRequest): Promise<CheckByIdResponse> | Observable<CheckByIdResponse> | CheckByIdResponse;
}

export function UsersServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["checkUser", "checkById"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UsersService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UsersService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USERS_SERVICE_NAME = "UsersService";
