<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: game_service.proto

namespace Game;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>game.CheckGameResponse</code>
 */
class CheckGameResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool exists = 1;</code>
     */
    protected $exists = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $exists
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GameService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool exists = 1;</code>
     * @return bool
     */
    public function getExists()
    {
        return $this->exists;
    }

    /**
     * Generated from protobuf field <code>bool exists = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setExists($var)
    {
        GPBUtil::checkBool($var);
        $this->exists = $var;

        return $this;
    }

}

