<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: game_service.proto

namespace Game;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>game.GameInfoResponse</code>
 */
class GameInfoResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string gameId = 1;</code>
     */
    protected $gameId = '';
    /**
     * Generated from protobuf field <code>string status = 2;</code>
     */
    protected $status = '';
    /**
     * Generated from protobuf field <code>int32 maxPlayers = 3;</code>
     */
    protected $maxPlayers = 0;
    /**
     * Generated from protobuf field <code>int32 totalRounds = 4;</code>
     */
    protected $totalRounds = 0;
    /**
     * Generated from protobuf field <code>int32 turnTime = 5;</code>
     */
    protected $turnTime = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $gameId
     *     @type string $status
     *     @type int $maxPlayers
     *     @type int $totalRounds
     *     @type int $turnTime
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GameService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string gameId = 1;</code>
     * @return string
     */
    public function getGameId()
    {
        return $this->gameId;
    }

    /**
     * Generated from protobuf field <code>string gameId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setGameId($var)
    {
        GPBUtil::checkString($var, True);
        $this->gameId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string status = 2;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 maxPlayers = 3;</code>
     * @return int
     */
    public function getMaxPlayers()
    {
        return $this->maxPlayers;
    }

    /**
     * Generated from protobuf field <code>int32 maxPlayers = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxPlayers($var)
    {
        GPBUtil::checkInt32($var);
        $this->maxPlayers = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 totalRounds = 4;</code>
     * @return int
     */
    public function getTotalRounds()
    {
        return $this->totalRounds;
    }

    /**
     * Generated from protobuf field <code>int32 totalRounds = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setTotalRounds($var)
    {
        GPBUtil::checkInt32($var);
        $this->totalRounds = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 turnTime = 5;</code>
     * @return int
     */
    public function getTurnTime()
    {
        return $this->turnTime;
    }

    /**
     * Generated from protobuf field <code>int32 turnTime = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setTurnTime($var)
    {
        GPBUtil::checkInt32($var);
        $this->turnTime = $var;

        return $this;
    }

}

