<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: game_service.proto

namespace Game;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>game.GetGameRequest</code>
 */
class GetGameRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string gameId = 1;</code>
     */
    protected $gameId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $gameId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GameService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string gameId = 1;</code>
     * @return string
     */
    public function getGameId()
    {
        return $this->gameId;
    }

    /**
     * Generated from protobuf field <code>string gameId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setGameId($var)
    {
        GPBUtil::checkString($var, True);
        $this->gameId = $var;

        return $this;
    }

}

